'use client';

import React from 'react';
import Link from 'next/link';
import Hero from '@/components/hero/Hero';
import { motion } from 'motion/react';
import { 
  Sparkles, Compass, MapPin, DollarSign, ShieldCheck, 
  Layers, ArrowRight, Zap, CheckCircle2, MessageSquare, Globe
} from 'lucide-react';

const FEATURED_DESTINATIONS = [
  {
    name: 'Pokhara, Nepal',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    days: '5 Days',
    budget: 'NPR 42,000',
    tag: 'Adventure & Lakes',
  },
  {
    name: 'Kyoto, Japan',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    days: '7 Days',
    budget: '¥ 180,000',
    tag: 'Culture & Temples',
  },
  {
    name: 'Paris, France',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    days: '4 Days',
    budget: '€ 1,200',
    tag: 'Romance & Cuisine',
  },
  {
    name: 'Bali, Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    days: '6 Days',
    budget: 'USD $850',
    tag: 'Relaxation & Beaches',
  },
];

const HOW_IT_WORKS = [
  {
    step: '01',
    title: 'Enter Preferences',
    desc: 'Specify your destination, dates, budget tier, and travel style (Adventure, Food, Culture, Relaxation).',
    icon: Compass,
  },
  {
    step: '02',
    title: 'Gemini AI Generates Itinerary',
    desc: 'Our Gemini AI engine crafts a custom day-by-day schedule enriched with real coordinates and place data.',
    icon: Sparkles,
  },
  {
    step: '03',
    title: 'Explore & Customize',
    desc: 'Visualize on interactive maps, optimize your budget, and chat with AI to tweak your trip in real time.',
    icon: Globe,
  },
];

const SaaS_FEATURES = [
  {
    title: 'Gemini 3.6 Flash Engine',
    desc: 'Ultra-fast structured AI responses ensuring exact time slots, realistic costs, and custom activity pacing.',
    icon: Zap,
  },
  {
    title: 'Google Places Integration',
    desc: 'Enriched real-world locations complete with place ratings, addresses, opening hours, and photos.',
    icon: MapPin,
  },
  {
    title: 'Interactive Mapbox Maps',
    desc: 'Dynamic color-coded activity markers, popups, polyline route paths, and dark/light vector themes.',
    icon: Compass,
  },
  {
    title: 'Contextual AI Travel Assistant',
    desc: 'Conversational assistant enabling live natural language edits to your itinerary on the fly.',
    icon: MessageSquare,
  },
];

export default function HomePage() {
  return (
    <div className="space-y-20 pb-20">
      {/* Hero Section */}
      <Hero />

      {/* Explore Featured Routes Section */}
      <section id="explore" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-10 gap-4">
          <div className="space-y-2">
            <span className="text-xs font-bold uppercase tracking-wider text-indigo-600 dark:text-cyan-400">
              Popular Destinations
            </span>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-neutral-900 dark:text-white tracking-tight">
              Featured AI Travel Routes
            </h2>
            <p className="text-sm text-neutral-500 dark:text-neutral-400 max-w-lg">
              Explore curated itineraries generated by travelers using Voyara AI.
            </p>
          </div>

          <Link
            href="/create-trip"
            className="px-5 py-2.5 rounded-2xl bg-neutral-900 dark:bg-neutral-100 text-white dark:text-neutral-900 text-xs font-bold hover:scale-105 transition-all self-start md:self-auto flex items-center gap-1.5"
          >
            Create Custom Trip <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {FEATURED_DESTINATIONS.map((dest) => (
            <div
              key={dest.name}
              className="group relative rounded-3xl overflow-hidden border border-neutral-200/80 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-md hover:shadow-xl transition-all h-[340px] flex flex-col justify-end p-5"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={dest.image}
                alt={dest.name}
                className="absolute inset-0 w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-neutral-950/90 via-neutral-950/30 to-transparent" />

              <div className="relative z-10 space-y-2 text-white">
                <span className="px-2.5 py-1 rounded-full bg-white/20 backdrop-blur-md text-[10px] font-bold text-cyan-300 uppercase tracking-wider border border-white/20">
                  {dest.tag}
                </span>
                <h3 className="text-xl font-extrabold">{dest.name}</h3>
                <div className="flex items-center justify-between text-xs text-neutral-300 font-medium pt-1">
                  <span>{dest.days}</span>
                  <span className="font-bold text-emerald-400">{dest.budget}</span>
                </div>
                <Link
                  href="/create-trip"
                  className="w-full mt-2 py-2 rounded-xl bg-white/10 hover:bg-white/20 backdrop-blur-md text-xs font-bold text-center block transition-all border border-white/20"
                >
                  Plan Similar Trip
                </Link>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* How It Works Section */}
      <section id="how-it-works" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="text-center max-w-2xl mx-auto space-y-3 mb-12">
          <span className="text-xs font-bold uppercase tracking-wider text-indigo-600 dark:text-cyan-400">
            Simple & Seamless
          </span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-neutral-900 dark:text-white tracking-tight">
            How Voyara AI Works
          </h2>
          <p className="text-sm text-neutral-500 dark:text-neutral-400">
            From idea to complete itinerary in under 10 seconds.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {HOW_IT_WORKS.map((hw) => {
            const Icon = hw.icon;
            return (
              <div
                key={hw.step}
                className="relative p-8 rounded-3xl border border-neutral-200/80 dark:border-neutral-800 bg-white/60 dark:bg-neutral-900/60 backdrop-blur-md shadow-md space-y-4 text-left group hover:border-indigo-500/50 transition-all"
              >
                <div className="flex items-center justify-between">
                  <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-indigo-600 to-cyan-500 text-white flex items-center justify-center shadow-lg shadow-indigo-500/20">
                    <Icon className="w-6 h-6" />
                  </div>
                  <span className="text-2xl font-black text-neutral-300 dark:text-neutral-700">
                    {hw.step}
                  </span>
                </div>

                <h3 className="text-xl font-bold text-neutral-900 dark:text-white">
                  {hw.title}
                </h3>

                <p className="text-xs text-neutral-600 dark:text-neutral-400 leading-relaxed">
                  {hw.desc}
                </p>
              </div>
            );
          })}
        </div>
      </section>

      {/* Features SaaS Section */}
      <section id="features" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-neutral-900 text-white rounded-3xl p-8 md:p-12 border border-neutral-800 shadow-2xl relative overflow-hidden space-y-10">
          <div className="max-w-xl space-y-3">
            <span className="text-xs font-bold uppercase tracking-wider text-cyan-400 flex items-center gap-1">
              <Sparkles className="w-3.5 h-3.5" /> Next-Gen AI Platform
            </span>
            <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
              Engineered for demanding travelers.
            </h2>
            <p className="text-xs sm:text-sm text-neutral-400 leading-relaxed">
              Voyara AI blends Google Gemini structured content, Google Places APIs, and Mapbox geospatial data into a unified SaaS experience.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {SaaS_FEATURES.map((sf) => {
              const Icon = sf.icon;
              return (
                <div
                  key={sf.title}
                  className="p-6 rounded-2xl bg-neutral-950/60 border border-neutral-800/80 space-y-3 hover:border-cyan-500/50 transition-all"
                >
                  <div className="w-10 h-10 rounded-xl bg-indigo-500/20 text-cyan-400 flex items-center justify-center">
                    <Icon className="w-5 h-5" />
                  </div>
                  <h4 className="font-bold text-base text-white">{sf.title}</h4>
                  <p className="text-xs text-neutral-400 leading-relaxed">{sf.desc}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Final Call To Action Banner */}
      <section className="max-w-4xl mx-auto px-4 text-center space-y-6 pt-10">
        <h2 className="text-3xl sm:text-4xl font-extrabold text-neutral-900 dark:text-white tracking-tight">
          Ready for your next adventure?
        </h2>
        <p className="text-sm text-neutral-600 dark:text-neutral-400 max-w-lg mx-auto">
          Start planning your personalized journey now with AI recommendations, real map routes, and budget tracking.
        </p>
        <Link
          href="/create-trip"
          className="inline-flex items-center gap-2 px-8 py-4 rounded-2xl bg-gradient-to-r from-indigo-600 via-violet-600 to-cyan-500 text-white font-bold text-base shadow-xl shadow-indigo-500/25 hover:scale-105 transition-all"
        >
          <Sparkles className="w-5 h-5" /> Plan My Trip Now
        </Link>
      </section>
    </div>
  );
}
