'use client';

import React from 'react';
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip } from 'recharts';
import { BudgetBreakdown } from '@/types/trip';
import { DollarSign, ShieldCheck, PieChart as PieChartIcon, TrendingUp } from 'lucide-react';

interface BudgetVisualizerProps {
  breakdown: BudgetBreakdown;
  currency: string;
  totalBudget: number;
}

const COLORS = ['#3b82f6', '#f59e0b', '#06b6d4', '#10b981', '#8b5cf6'];

export default function BudgetVisualizer({
  breakdown,
  currency,
  totalBudget
}: BudgetVisualizerProps) {
  const chartData = [
    { name: 'Accommodation', value: breakdown.accommodation || 0 },
    { name: 'Food', value: breakdown.food || 0 },
    { name: 'Transportation', value: breakdown.transportation || 0 },
    { name: 'Activities', value: breakdown.activities || 0 },
    { name: 'Miscellaneous', value: breakdown.miscellaneous || 0 },
  ].filter(item => item.value > 0);

  // Calculate budget health percentage (comparison against default threshold)
  const healthPercent = Math.min(100, Math.round((breakdown.total / (totalBudget || breakdown.total || 1)) * 100));

  return (
    <div className="bg-white dark:bg-neutral-900 border border-neutral-200/80 dark:border-neutral-800 rounded-3xl p-6 shadow-md space-y-6">
      <div className="flex items-center justify-between border-b border-neutral-100 dark:border-neutral-800 pb-4">
        <div>
          <h3 className="font-bold text-lg text-neutral-900 dark:text-white flex items-center gap-2">
            <PieChartIcon className="w-5 h-5 text-indigo-500" />
            Estimated Trip Budget
          </h3>
          <p className="text-xs text-neutral-500 dark:text-neutral-400">
            Categorized cost optimization generated by Voyara AI
          </p>
        </div>

        <div className="text-right">
          <span className="text-xs text-neutral-400 font-medium">Total Cost</span>
          <p className="text-2xl font-black text-emerald-600 dark:text-emerald-400">
            {currency} {breakdown.total?.toLocaleString() || totalBudget?.toLocaleString()}
          </p>
        </div>
      </div>

      {/* Chart & Legend Grid */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-center">
        {/* Pie Chart */}
        <div className="md:col-span-5 h-[220px] relative flex items-center justify-center">
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie
                data={chartData}
                cx="50%"
                cy="50%"
                innerRadius={55}
                outerRadius={85}
                paddingAngle={4}
                dataKey="value"
              >
                {chartData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip 
                formatter={(val: any) => `${currency} ${Number(val).toLocaleString()}`}
                contentStyle={{ borderRadius: '12px', background: '#09090b', color: '#fff', border: '1px solid #27272a' }}
              />
            </PieChart>
          </ResponsiveContainer>

          <div className="absolute text-center pointer-events-none">
            <span className="text-[10px] text-neutral-400 font-bold uppercase">Budget</span>
            <p className="text-sm font-black text-neutral-800 dark:text-neutral-100">
              {currency} {breakdown.total ? Math.round(breakdown.total / 1000) + 'k' : ''}
            </p>
          </div>
        </div>

        {/* Legend List */}
        <div className="md:col-span-7 space-y-2.5">
          {chartData.map((item, idx) => {
            const pct = breakdown.total ? Math.round((item.value / breakdown.total) * 100) : 0;
            return (
              <div key={item.name} className="flex items-center justify-between text-xs p-2 rounded-xl bg-neutral-50 dark:bg-neutral-950/40 border border-neutral-100 dark:border-neutral-800">
                <div className="flex items-center gap-2">
                  <span className="w-3 h-3 rounded-full" style={{ backgroundColor: COLORS[idx % COLORS.length] }} />
                  <span className="font-semibold text-neutral-800 dark:text-neutral-200">{item.name}</span>
                </div>
                <div className="flex items-center gap-3">
                  <span className="text-neutral-400 font-medium">{pct}%</span>
                  <span className="font-bold text-neutral-900 dark:text-white">
                    {currency} {item.value.toLocaleString()}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Budget Health Meter */}
      <div className="pt-4 border-t border-neutral-100 dark:border-neutral-800 space-y-2">
        <div className="flex items-center justify-between text-xs">
          <span className="font-bold text-neutral-700 dark:text-neutral-300 flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-500" />
            Budget Health
          </span>
          <span className="font-semibold text-emerald-600 dark:text-emerald-400">
            {healthPercent}% - Within Optimal Range
          </span>
        </div>

        <div className="w-full bg-neutral-100 dark:bg-neutral-800 h-3 rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-emerald-500 via-indigo-500 to-cyan-400 transition-all duration-500"
            style={{ width: `${Math.min(100, healthPercent)}%` }}
          />
        </div>
      </div>
    </div>
  );
}
